import Head from "next/head";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Food - Your Delivery</title>
        <meta name="description" content="Generated by virtualdev.de" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {children}
      <Footer />
    </div>
  );
}
