const jsondb = {
  products: [
    {
      name: "Salami",
      description: "Tomato sauce, cheese, salami",
      category: "Main menu",
      price: 6.99,
      url: "pizza",
      picture: "/pictures/products/pizza1.jpg",
    },
    {
      name: "Prosciutto",
      description: "Tomato sauce, cheese, ham",
      category: "Main menu",
      price: 7.99,
      url: "pizza",
      picture: "/pictures/products/pizza2.jpg",
    },
    {
      name: "Mushrooms",
      description: "Tomato sauce, cheese, Mushrooms",
      category: "Main menu",
      price: 8.99,
      url: "pizza",
      picture: "/pictures/products/pizza3.jpg",
    },
    {
      name: "Mushrooms",
      description: "Tomato sauce, cheese, Mushrooms",
      category: "Main menu",
      price: 8.99,
      url: "pizza",
      picture: "/pictures/products/pizza4.jpg",
    },
    {
      name: "Beef",
      description: "Tomato sauce, cheese, ham, olives",
      category: "Main menu",
      price: 8.99,
      url: "pizza",
      picture: "/pictures/products/pizza5.jpg",
    },
    {
      name: "Italia",
      description: "Tomato sauce, cheese, chicken, olives, red peppers",
      category: "Main menu",
      price: 8.99,
      url: "pizza",
      picture: "/pictures/products/pizza8.jpg",
    },
    {
      name: "Hang Loose",
      description: "Tomato sauce, cheese, chicken, olives, red peppers",
      category: "Drinks",
      price: 3.99,
      url: "drinks",
      picture: "/pictures/products/beer.png",
    },
    {
      name: "Vanilla Ice",
      description: "Vanilla ice, maple syrup,",
      category: "dessert",
      price: 3.99,
      url: "dessert",
      picture: "/pictures/products/dessert1.jpg",
    },
    {
      name: "Brownie",
      description: "Brownie chocolate",
      category: "dessert",
      price: 2.99,
      url: "dessert",
      picture: "/pictures/products/dessert2.jpg",
    },
    {
      name: "Muffin",
      description: "Chocolate, white chocolate, raspberry",
      category: "dessert",
      price: 2.99,
      url: "dessert",
      picture: "/pictures/products/dessert3.jpg",
    },
  ],
};

export default jsondb;
